### ISSUE TITLE
ActiveRecord 5.0.1 error

### ISSUE THREAD

**Issue by esambo** [enova/active_record_stats#3]
I get following error after upgrading from ActiveRecord 5.0.0.1 to 5.0.1:
`ArgumentError: A value is required for metric type :ms.`
```
statsd/instrument/metric.rb in default_value at line 66
statsd/instrument/metric.rb in initialize at line 51
statsd/instrument.rb in new at line 394
statsd/instrument.rb in collect_metric at line 394
statsd/instrument.rb in measure at line 288
active_record_stats/rack_middleware.rb in emit at line 59
active_record_stats/rack_middleware.rb in call at line 48
```

**Comment by jefflunt** [comment]
Ran into a similar problem today. Seems that, for whatever reason, the value for `db_time` isn't being set. Can't reproduce this locally, but someone else on my team has been able to reproduce it on a popops box. So if I can track it down (and reproduce it reliably) I'll update this issue.

**Comment by jefflunt** [comment]
I can reproduce this in the following way, using Rails 5.0.1

* Enable the gem and middleware
* Start the app in production mode, locally
* Hit a page in your app that doesn't make any SQL queries

This will cause the `:db_runtime` key in the payload for the `process_action.action_controller` notification to not be present, which causes this gem to pass `nil` to `Statsd`, which throws the error in question.

If you then hit a page in your app that runs a SQL query, all subsequent calls into this gem work fine without restarting the app.

It's totally possible that the issue is in my app's config, but haven't been able to track it down.

**Comment by jefflunt** [comment]
If you're experiencing this issue, then a simple workaround is to force a SQL call, via ActiveRecord, in an app initializer so that no matter what app endpoint you hit first the `ActiveSupport::Notifications` behavior will work as expected.

Something as simple as `ActiveRecord::Base.connection.active?` will usually work.

**Comment by jefflunt** [comment]
Well [here it is](https://github.com/rails/rails/commit/8a722e09122a2beeb122a8931a08b72c46d6bc50#diff-943cb4f9eea36329a444c673684be687R35): the reason the `:db_runtime` key isn't always present is because there was a conditional added 6 years ago, wrapped around the adding of the key, and based on whether or not ActiveRecord is connected.

That explains the symptoms, and why a workaround of forcing the ActiveRecord connection works. Now I'm off to see why the behavior is different between my `development` and `staging / production` environments.

**Comment by jefflunt** [comment]
So, here's the deal:

### Why was this happening only in `development`?

* Check your environment for `config.active_record.migration_error = :page_load`
* If it's present, then `ActiveRecord` will check for pending migrations while starting your app
  * Checking for pending migrations requires an active connection to the database
    * Connecting to the database allows [this condition in ActiveRecord](https://github.com/rails/rails/commit/8a722e09122a2beeb122a8931a08b72c46d6bc50#diff-943cb4f9eea36329a444c673684be687R35) to evaluate to `true`, which is where the `:db_runtime` key is added to the `process_action.action_controller` payload

NOTE: Any other config option that forces a database connection when the app is started will have the same effect. It just happens that `config.active_record.migration_error` was the option that triggered it in my app.

---

At this point I don't think it's the gem's responsibility to check whether or not the `:db_runtime` key is present, since [the documentation](http://guides.rubyonrails.org/active_support_instrumentation.html#process-action-action-controller) doesn't say that it might be nil/not present. I think it might be an oversight in ActiveRecord -- but we'll see.
